server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  application:
    name: shop-app-test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages_ko
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
