server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: shop-app
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  messages:
    basename: messages_ko
    encoding: UTF-8
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html